const data = {
  products: [
    {
      name: 'Jordan 4s Military',
      price: 240.0,
      description: 'The basic package with only 1 video that last 30 - 60secs.',
      image: '/Images/jordan4',
      category: 'shoes',
      vedette: true,
    },
    {
      name: 'Nike Air Max Plus',
      price: 175.0,
      description: 'The basic package with only 1 video that last 30 - 60secs.',
      image: '/Images/tn',
      category: 'shoes',
      vedette: true,
    },
    {
      name: 'Yeezy Boost 700 V1',
      price: 220.0,
      description: 'The basic package with only 1 video that last 30 - 60secs.',
      image: '/Images/yeezy700',
      category: 'shoes',
      vedette: true,
    },
    {
      name: 'Nike Air Jordan 1',
      price: 220.0,
      description: 'The basic package with only 1 video that last 30 - 60secs.',
      image: '/Images/aj1',
      category: 'shoes',
      vedette: true,
    },
    {
      name: 'Nike Tech Fleece Blanc',
      price: 200.0,
      description: 'The basic package with only 1 video that last 30 - 60secs.',
      image: '/Images/nt-white',
      category: 'clothes',
      vedette: true,
    },
    {
      name: 'Nike Tech Fleece Marin',
      price: 200.0,
      description: 'The basic package with only 1 video that last 30 - 60secs.',
      image: '/Images/nt-blue.jpg',
      category: 'clothes',
      vedette: true,
    },
    {
      name: 'Nike Tech Fleece Gris',
      price: 200.0,
      description: 'The basic package with only 1 video that last 30 - 60secs.',
      image: '/Images/nt-black.png',
      category: 'clothes',
      vedette: true,
    },
    {
      name: 'Survetement X Drake',
      price: 200.0,
      description: 'The basic package with only 1 video that last 30 - 60secs.',
      image: '/Images/x-surv.png',
      category: 'clothes',
      vedette: true,
    },
  ],
};

export default data;
